FROM alpine:edge

# Install mongodb, node + npm
RUN apk update && apk add \
  mongodb --update-cache \
    --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
    --allow-untrusted

# Setup mongodb directories
VOLUME /data/db /mongodb/backup

EXPOSE 27017

CMD ["mongod"]
